version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run linter
          command: npm run lint
